name: buildUpload

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
       
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
     
      - name: Restore NuGet Packages
        run: nuget restore Fenester.sln
 
      - name: Build and Publish Web App
        run: msbuild Fenester.sln /p:Configuration=Release
 
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Fenester.Exe.InteractiveTest
          path: Fenester.Exe.InteractiveTest\bin\Release
